# numpy的操作

In [1]:
list1 = [1, 2, 3]

In [2]:
list1

[1, 2, 3]

In [3]:
type(list1)

list

In [5]:
list2 = [[1, 2], [3, 4], [5, 6]]

In [6]:
list2

[[1, 2], [3, 4], [5, 6]]

In [7]:
type(list2)

list

In [8]:
list2[1][0]

3

# 如何创建一个numpy数组

In [9]:
import numpy as np

In [10]:
list3 = [1, 2, 3, 4]

In [11]:
my_array = np.array(list3)

In [12]:
type(my_array)

numpy.ndarray

In [13]:
my_array

array([1, 2, 3, 4])

In [14]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
np.ones(shape=(3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.ones(shape=(10, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.zeros(shape=(5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# numpy中对数组的操作

In [19]:
arr = np.random.randint(0, 100, 10)

In [20]:
arr

array([34,  5, 44, 90,  7, 79, 85,  7, 43, 52])

In [21]:
arr.max()

90

In [22]:
arr.min()

5

In [23]:
arr.argmax()

3

In [24]:
arr.argmin()

1

In [25]:
arr.mean()

44.6

In [27]:
arr.shape

(10,)

In [40]:
arr.reshape((2, 5))

array([[34,  5, 44, 90,  7],
       [79, 85,  7, 43, 52]])

In [42]:
arr.reshape((5, 2))

array([[34,  5],
       [44, 90],
       [ 7, 79],
       [85,  7],
       [43, 52]])

# numpy中对矩阵的操作

In [43]:
matrix = np.arange(0, 100).reshape((10, 10))

In [45]:
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [47]:
matrix.shape

(10, 10)

In [48]:
matrix[2, 4]

24

In [49]:
matrix[8, 7]

87

In [50]:
matrix[:, 2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [52]:
matrix[:, 2].reshape((10, 1))

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52],
       [62],
       [72],
       [82],
       [92]])

In [53]:
matrix[2, :]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [54]:
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [55]:
matrix[0:3, 1:4]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [56]:
matrix[0:3, 1:4] = 0

In [57]:
matrix

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [10,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [20,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])